### ISSUE TITLE
copy of my work

### ISSUE THREAD

**Issue by baigalmaa-baatar** [pasqualerossi/Born2BeRoot-Guide#10]
Hi,
It seems that you copied all the steps and guide, including shell scripts, from my Medium article [https://medium.com/@baigal/born2beroot-e6e26dfb50ac](https://medium.com/@baigal/born2beroot-e6e26dfb50ac)

can you add proper attribution to my original work in this repository or remove the copied content?

Baigalmaa BAATAR

**Comment by pasqualerossi** [comment]
Hi Baigalmaa BAATAR, 

At the time, we had completely forgot to add attribution to your great work. Thankyou for letting us know and for your great guide, attribution has now been added to this repository. 

Regards,
@pasqualerossi

**Comment by baigalmaa-baatar** [comment]
Thanks man ;)

**Comment by pasqualerossi** [comment]
Yw! :)
